### ISSUE TITLE
China maps seem to have coordinates displaced by some meters

### ISSUE THREAD

**Issue by Jmaguerre** [mapsme/api-ios#18]
Version 8.1.2.1

![img_3576](https://user-images.githubusercontent.com/961227/37594716-cbcc31fe-2b54-11e8-9cb9-ae4c9ed0ee72.PNG)

If I open the same coordinates in google maps they show the center of the place correctly. It does not happen with other countries.

**Comment by Zverik** [comment]
That is an issue with the chinese local map projection. Maps in Baidu and Google are offset, and OSM has the correct locations for any point of the world. [See this article](https://www.gearthblog.com/blog/archives/2015/08/chinese-street-maps-alignment-google-earth-google-maps.html) for example.

**Comment by Jmaguerre** [comment]
Thanks for the clarification
